apis = ["bitbucket"]

[bitbucket.info]
name = "BitBucket"
baseURL = "https://bitbucket.org"
code = 'site/oauth2/authorize?client_id={CLIENT_ID}&response_type=code'
access_token = 'site/oauth2/access_token'
